# Generated by Django 4.2.16 on 2024-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
