# Generated by Django 4.2.16 on 2024-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0002_video_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_file_es',
            field=models.FileField(blank=True, null=True, upload_to='subtitles_es/'),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_file_fr',
            field=models.FileField(blank=True, null=True, upload_to='subtitles_fr/'),
        ),
    ]
