# Generated by Django 4.2.16 on 2024-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0003_video_subtitle_file_es_video_subtitle_file_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_file_hi',
            field=models.FileField(blank=True, null=True, upload_to='subtitles_hi/'),
        ),
    ]
